/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  eta // clock
    , input  eta1 // reset
    , input  eta2 // enable

      // Outputs
    , output wire [1:0] currentState
    );
  // TrafficLight.hs:28:1-88
  reg [1:0] currentState_1 = 2'd1;
  // TrafficLight.hs:28:1-88
  reg [1:0] c$currentState_app_arg;
  // TrafficLight.hs:28:1-88
  reg [1:0] c$currentState_case_scrut;

  // register begin
  always @(posedge eta or  posedge  eta1) begin : currentState_1_register
    if ( eta1) begin
      currentState_1 <= 2'd1;
    end else if (eta2) begin
      currentState_1 <= c$currentState_app_arg;
    end
  end
  // register end

  always @(*) begin
    case(c$currentState_case_scrut)
      2'b00 : c$currentState_app_arg = 2'd2;
      2'b01 : c$currentState_app_arg = 2'd3;
      default : c$currentState_app_arg = 2'd1;
    endcase
  end

  always @(*) begin
    case(currentState_1)
      2'd1 : c$currentState_case_scrut = 2'd0;
      2'd2 : c$currentState_case_scrut = 2'd1;
      2'd3 : c$currentState_case_scrut = 2'd2;
      default : c$currentState_case_scrut = {2 {1'bx}};
    endcase
  end

  assign currentState = currentState_1;


endmodule

