/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  eta // clock
    , input  eta_0
    , input [3:0] eta1

      // Outputs
    , output reg [3:0] result
    );
  wire [0:0] result_selection_res;

  assign result_selection_res = (eta_0);

  always @(*) begin
    case(result_selection_res)
      1'b1 : result = 4'd0;
      default : result = eta1 + 4'd1;
    endcase
  end


endmodule

