/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input [7:0] a1
    , input [7:0] b

      // Outputs
    , output wire [7:0] result
    );


  assign result = a1 + b;


endmodule

