/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  eta // clock
    , input  eta1 // reset
    , input  eta2 // enable
    , input signed [31:0] eta_0

      // Outputs
    , output wire signed [31:0] result
    );
  reg signed [31:0] result_1 = 32'sd0;

  // register begin
  always @(posedge eta or  posedge  eta1) begin : result_1_register
    if ( eta1) begin
      result_1 <= 32'sd0;
    end else if (eta2) begin
      result_1 <= eta_0;
    end
  end
  // register end

  assign result = result_1;


endmodule

